server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: security
    password: tiger

  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 487664062068-ah6vdrfqah90hhn2edi1keim9q2eaf18.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile



logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type: trace

